from fetch_function import *

if __name__ == "__main__":
    data = get_full_data("intc", False, True)

    dict = {
        "dates": ("", data["financials"]["annual"]["period_end_date"]),
        "cash_and_equiv": ("Cash and Equivalents", data["financials"]["annual"]["cash_and_equiv"]),
        "st_investments": ("Short-Term Investments", data["financials"]["annual"]["st_investments"]),
        "receivables": ("Accounts Receivable", data["financials"]["annual"]["receivables"]),
        "inventories": ("Inventories", data["financials"]["annual"]["inventories"]),
        "other_current_assets": ("Other Current Assets", data["financials"]["annual"]["other_current_assets"]),
        "total_current_assets": ("Total Current Assets", data["financials"]["annual"]["total_current_assets"]),
        "equity_and_other_investments": ("Equity & Other Investments", data["financials"]["annual"]["equity_and_other_investments"]),
        "ppe_gross": ("Gross PPE", data["financials"]["annual"]["ppe_gross"]),
        "accumulated_depreciation": ("Accumulated Depreciation", data["financials"]["annual"]["accumulated_depreciation"]),
        "ppe_net": ("Net PPE", data["financials"]["annual"]["ppe_net"]),
        "intangible_assets": ("Intangible Assets", data["financials"]["annual"]["intangible_assets"]),
        "goodwill": ("Goodwill", data["financials"]["annual"]["goodwill"]),
        "other_lt_assets": ("Other Long-Term Assets", data["financials"]["annual"]["other_lt_assets"]),
        "total_assets": ("Total Assets", data["financials"]["annual"]["total_assets"]),
        "accounts_payable": ("Accounts Payable", data["financials"]["annual"]["accounts_payable"]),
        "tax_payable": ("Tax Payable", data["financials"]["annual"]["tax_payable"]),
        "current_accrued_liabilities": ("Current Accrued Liabilities", data["financials"]["annual"]["current_accrued_liabilities"]),
        "st_debt": ("Short-term Debt", data["financials"]["annual"]["st_debt"]),
        "current_deferred_revenue": ("Current Deferred Revenue", data["financials"]["annual"]["current_deferred_revenue"]),
        "current_deferred_tax_liability": ("Current Deferred Tax Liability", data["financials"]["annual"]["current_deferred_tax_liability"]),
        "current_capital_leases": ("Current Capital Lease Obligation", data["financials"]["annual"]["current_capital_leases"]),
        "other_current_liabilities": ("Other Current Liabilities", data["financials"]["annual"]["other_current_liabilities"]),
        "total_current_liabilities": ("Total Current Liabilities", data["financials"]["annual"]["total_current_liabilities"]),
        "lt_debt": ("Long-term Debt", data["financials"]["annual"]["lt_debt"]),
        "noncurrent_capital_leases": ("Capital Lease Obligation", data["financials"]["annual"]["noncurrent_capital_leases"]),
        "pension_liabilities": ("Pension Liabilities", data["financials"]["annual"]["pension_liabilities"]),
        "noncurrent_deferred_revenue": ("Noncurrent Deferred Revenue", data["financials"]["annual"]["noncurrent_deferred_revenue"]),
        "other_lt_liabilities": ("Other Long-Term Liabilities", data["financials"]["annual"]["other_lt_liabilities"]),
        "total_liabilities": ("Total Liabilities", data["financials"]["annual"]["total_liabilities"]),
        "common_stock": ("Common Stock", data["financials"]["annual"]["common_stock"]),
        "preferred_stock": ("Preferred Stock", data["financials"]["annual"]["preferred_stock"]),
        "retained_earnings": ("Retained Earnings", data["financials"]["annual"]["retained_earnings"]),
        "aoci": ("Accumulated Other Comprehensive Income", data["financials"]["annual"]["aoci"]),
        "apic": ("Additional Paid-in Capital", data["financials"]["annual"]["apic"]),
        "treasury_stock": ("Treasury Stock", data["financials"]["annual"]["treasury_stock"]),
        "other_equity": ("Other Equity", data["financials"]["annual"]["other_equity"]),
        "minority_interest_liability": ("Minority Interest Liability", data["financials"]["annual"]["minority_interest_liability"]),
        "total_equity": ("Total Equity", data["financials"]["annual"]["total_equity"]),
        "total_liabilities_and_equity": ("Total Liabilities & Equity", data["financials"]["annual"]["total_liabilities_and_equity"]),
        "total_investments": ("Total Investments", data["financials"]["annual"]["total_investments"]),
        "deferred_policy_acquisition_cost": ("Deferred Policy Acquisition Costs", data["financials"]["annual"]["deferred_policy_acquisition_cost"]),
        "unearned_premiums": ("Unearned Premiums", data["financials"]["annual"]["unearned_premiums"]),
        "future_policy_benefits": ("Future Policy Benefits", data["financials"]["annual"]["future_policy_benefits"]),
        "loans_gross": ("Gross Loans", data["financials"]["annual"]["loans_gross"]),
        "allowance_for_loan_losses": ("Allowance for Loan Losses", data["financials"]["annual"]["allowance_for_loan_losses"]),
        "unearned_income": ("Unearned Income", data["financials"]["annual"]["unearned_income"]),
        "loans_net": ("Net Loans", data["financials"]["annual"]["loans_net"]),
        "deposits_liability": ("Total Deposits", data["financials"]["annual"]["deposits_liability"]),
    }