from fetch_function import *

if __name__ == "__main__":
    data = get_full_data("intc", False, True)

    dict = {
        "dates": ("", data["financials"]["annual"]["period_end_date"]),
        "cfo_net_income": ("Net Income (Cash Flow Statement)", data["financials"]["annual"]["cfo_net_income"]),
        "cfo_da": ("Depreciation, Depletion, & Amortization", data["financials"]["annual"]["cfo_da"]),
        "cfo_receivables": ("Change in Receivables", data["financials"]["annual"]["cfo_receivables"]),
        "cfo_inventory": ("Change in Inventory", data["financials"]["annual"]["cfo_inventory"]),
        "cfo_prepaid_expenses": ("Change in Prepaid Assets", data["financials"]["annual"]["cfo_prepaid_expenses"]),
        "cfo_other_working_capital": ("Change in Other Working Capital", data["financials"]["annual"]["cfo_other_working_capital"]),
        "cfo_change_in_working_capital": ("Change in Working Capital", data["financials"]["annual"]["cfo_change_in_working_capital"]),
        "cfo_deferred_tax": ("Change in Deferred Tax", data["financials"]["annual"]["cfo_deferred_tax"]),
        "cfo_stock_comp": ("Stock Compensation", data["financials"]["annual"]["cfo_stock_comp"]),
        "cfo_other_noncash_items": ("Other Cash from Operations", data["financials"]["annual"]["cfo_other_noncash_items"]),
        "cf_cfo": ("Cash from Operations", data["financials"]["annual"]["cf_cfo"]),
        "cfi_ppe_purchases": ("Cash from Purchases of PPE", data["financials"]["annual"]["cfi_ppe_purchases"]),
        "cfi_ppe_sales": ("Cash from Sales of PPE", data["financials"]["annual"]["cfi_ppe_sales"]),
        "cfi_ppe_net": ("Net Purchases of PPE", data["financials"]["annual"]["cfi_ppe_net"]),
        "cfi_acquisitions": ("Cash from Acquisitions", data["financials"]["annual"]["cfi_acquisitions"]),
        "cfi_divestitures": ("Cash from Divestitures", data["financials"]["annual"]["cfi_divestitures"]),
        "cfi_acquisitions_net": ("Net Cash From Acquisitions and Divestitures", data["financials"]["annual"]["cfi_acquisitions_net"]),
        "cfi_investment_purchases": ("Cash from Purchases of Investments", data["financials"]["annual"]["cfi_investment_purchases"]),
        "cfi_investment_sales": ("Cash from Sales of Investments", data["financials"]["annual"]["cfi_investment_sales"]),
        "cfi_investment_net": ("Net Purchases of Investments", data["financials"]["annual"]["cfi_investment_net"]),
        "cfi_intangibles_net": ("Net Purchases of Intangible Assets", data["financials"]["annual"]["cfi_intangibles_net"]),
        "cfi_other": ("Other Cash from Investing", data["financials"]["annual"]["cfi_other"]),
        "cf_cfi": ("Cash from Investing", data["financials"]["annual"]["cf_cfi"]),
        "cff_common_stock_issued": ("Common Stock Issued", data["financials"]["annual"]["cff_common_stock_issued"]),
        "cff_common_stock_repurchased": ("Common Stock Repurchased", data["financials"]["annual"]["cff_common_stock_repurchased"]),
        "cff_common_stock_net": ("Net Issuance of Common Stock", data["financials"]["annual"]["cff_common_stock_net"]),
        "cff_pfd_issued": ("Preferred Stock Issued", data["financials"]["annual"]["cff_pfd_issued"]),
        "cff_pfd_repurchased": ("Preferred Stock Repurchased", data["financials"]["annual"]["cff_pfd_repurchased"]),
        "cff_pfd_net": ("Net Issuance of Preferred Stock", data["financials"]["annual"]["cff_pfd_net"]),
        "cff_debt_issued": ("Total Debt Issued", data["financials"]["annual"]["cff_debt_issued"]),
        "cff_debt_repaid": ("Total Debt Repaid", data["financials"]["annual"]["cff_debt_repaid"]),
        "cff_debt_net": ("Net Issuance of Debt", data["financials"]["annual"]["cff_debt_net"]),
        "cff_dividend_paid": ("Cash Paid for Dividends", data["financials"]["annual"]["cff_dividend_paid"]),
        "cff_other": ("Other Cash from Financing", data["financials"]["annual"]["cff_other"]),
        "cf_cff": ("Cash from Financing", data["financials"]["annual"]["cf_cff"]),
        "cf_forex": ("Foreign Exchange Adjustments", data["financials"]["annual"]["cf_forex"]),
        "cf_net_change_in_cash": ("Net Change in Cash", data["financials"]["annual"]["cf_net_change_in_cash"]),
    }
