from fetch_function import *

if __name__ == "__main__":
    data = get_full_data("intc", False, True)

    dict = {
        "dates": ("", data["financials"]["annual"]["period_end_date"]),
        "revenue": ("Revenue", data["financials"]["annual"]["revenue"]),
        "cogs": ("Cost of Goods Sold", data["financials"]["annual"]["cogs"]),
        "gross_profit": ("Gross Profit", data["financials"]["annual"]["gross_profit"]),
        "sga": ("Sales, General, & Administrative", data["financials"]["annual"]["sga"]),
        "rnd": ("Research & Development", data["financials"]["annual"]["rnd"]),
        "special_charges": ("Special Charges", data["financials"]["annual"]["special_charges"]),
        "other_opex": ("Other Operating Expense", data["financials"]["annual"]["other_opex"]),
        "total_opex": ("Total Operating Expense", data["financials"]["annual"]["total_opex"]),
        "operating_income": ("Operating Profit", data["financials"]["annual"]["operating_income"]),
        "interest_income": ("Interest Income", data["financials"]["annual"]["interest_income"]),
        "interest_expense": ("Interest Expense", data["financials"]["annual"]["interest_expense"]),
        "net_interest_income_normal": ("Net Interest Income (Non-financial)", data["financials"]["annual"]["net_interest_income_normal"]),
        "other_nonoperating_income": ("Other Income (Expense)", data["financials"]["annual"]["other_nonoperating_income"]),
        "pretax_income": ("Pre-Tax Profit", data["financials"]["annual"]["pretax_income"]),
        "income_tax": ("Income Tax", data["financials"]["annual"]["income_tax"]),
        "net_income_continuing": ("Earnings from Continuing Operations", data["financials"]["annual"]["net_income_continuing"]),
        "net_income_discontinued": ("Earnings from Discontinued Operations", data["financials"]["annual"]["net_income_discontinued"]),
        "income_allocated_to_minority_interest": ("Minority Interest Income", data["financials"]["annual"]["income_allocated_to_minority_interest"]),
        "income_allocated_to_minority_interest": ("Other Income Statement Items", data["financials"]["annual"]["income_allocated_to_minority_interest"]),
        "net_income": ("Net Income", data["financials"]["annual"]["net_income"]),
        "preferred_dividends": ("Preferred Dividends", data["financials"]["annual"]["preferred_dividends"]),
        "net_income_available_to_shareholders": ("Net Income Available to Shareholders", data["financials"]["annual"]["net_income_available_to_shareholders"]),
        "eps_basic": ("Basic EPS", data["financials"]["annual"]["eps_basic"]),
        "eps_diluted": ("Diluted EPS", data["financials"]["annual"]["eps_diluted"]),
        "shares_basic": ("Basic Shares Outstanding", data["financials"]["annual"]["shares_basic"]),
        "shares_diluted": ("Diluted Shares Outstanding", data["financials"]["annual"]["shares_diluted"]),
        "shares_eop": ("Shares Outstanding (End of Period)", data["financials"]["annual"]["shares_eop"]),
        "shares_eop_change": ("Shares Outstanding (End of Period) Change", data["financials"]["annual"]["shares_eop_change"]),
        "premiums_earned": ("Total Premiums Earned", data["financials"]["annual"]["premiums_earned"]),
        "net_investment_income": ("Net Investment Income", data["financials"]["annual"]["net_investment_income"]),
        "fees_and_other_income": ("Services, Fees, & Commissions", data["financials"]["annual"]["fees_and_other_income"]),
        "net_policyholder_claims_expense": ("Policy Claims & Benefits", data["financials"]["annual"]["net_policyholder_claims_expense"]),
        "policy_acquisition_expense": ("Policy Acquisition Expense", data["financials"]["annual"]["policy_acquisition_expense"]),
        "interest_expense_insurance": ("Interest Expense (Insurance)", data["financials"]["annual"]["interest_expense_insurance"]),
        "total_interest_income": ("Total Interest Income", data["financials"]["annual"]["total_interest_income"]),
        "total_interest_expense": ("Total Interest Expense", data["financials"]["annual"]["total_interest_expense"]),
        "net_interest_income": ("Net Interest Income", data["financials"]["annual"]["net_interest_income"]),
        "total_noninterest_revenue": ("Total Noninterest Revenue", data["financials"]["annual"]["total_noninterest_revenue"]),
        "credit_losses_provision": ("Credit Losses Provision", data["financials"]["annual"]["credit_losses_provision"]),
        "net_interest_income_after_credit_losses_provision": ("Net Interest Income After Credit Losses Provision", data["financials"]["annual"]["net_interest_income_after_credit_losses_provision"]),
        "total_noninterest_expense": ("Total Noninterest Expense", data["financials"]["annual"]["total_noninterest_expense"]),
        "da_income_statement_supplemental": ("Depreciation & Amortization (Supplemental Income Statement Item)", data["financials"]["annual"]["da_income_statement_supplemental"]),
    }
